### ISSUE TITLE
Missing output.css file.

### ISSUE THREAD

**Issue by sa-qib** [danihodovic/django-allauth-ui#137]
Allauth-UI is **missing** a ouput.css file in static, there is a input.css file but no **output**.

**Comment by danihodovic** [comment]
Fixed in 1.6.1

**Comment by SiddWilson** [comment]
I have 1.6.1 installed and it does not fix the missing output.css file.

**Comment by sa-qib** [comment]
nope I updated the installed repo and its still missing output.css.

**Comment by danihodovic** [comment]
Can you remind me what the output.css file is used for? I've installed 1.6.1 on https://django-allauth-ui.hodovi.ch and while it's missing output.css, it's successfully loading the css.

![Image](https://github.com/user-attachments/assets/9e85e6eb-95ae-4857-95b4-c590ff1aafd0)

**Comment by jayantipesa** [comment]
Hey @danihodovic , there's one more warning along with this error, if that helps:
<img width="941" alt="Image" src="https://github.com/user-attachments/assets/e9bc43f4-1f0b-4d01-bd90-0c1d1dc6013d" />

UI
<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/ebb7bd40-ff44-420e-87b7-408dfc514250" />

**Comment by danihodovic** [comment]
My bad, I'll see if I can resolve it next week. Sorry about that guys.

Downgrade for now.

**Comment by MOHD123ANAS** [comment]
Still, the error is not resolved I'm facing the same issue 

![Image](https://github.com/user-attachments/assets/9fa1f9dd-2443-4d3e-bf86-f047c764193c)

**Comment by danihodovic** [comment]
Fixed in 1.7.0

**Comment by joej** [comment]
Yet, just pulled down 1.7.1 and I get the exact same error (components.yaml not found)

**Comment by danihodovic** [comment]
> Yet, just pulled down 1.7.1 and I get the exact same error (components.yaml not found)

You can ignore the warnings by setting SILENCED_SYSTEM_CHECKS

https://stackoverflow.com/questions/29562070/how-to-suppress-the-deprecation-warnings-in-django

**Comment by abe-101** [comment]
I'm getting this error after attempting to deploy and upgrade from 1.5.3 to 1.8.1
```shell
Post-processing 'allauth_ui/input.css' failed!
 
Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    main()
    ~~~~^^
  File "/app/manage.py", line 27, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/opt/venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/django/core/management/base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.13/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/opt/venv/lib/python3.13/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'allauth_ui/tailwindcss' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f0fe1fe02f0>.
 
The CSS file 'allauth_ui/input.css' references a file which could not be found:
  allauth_ui/tailwindcss
 
Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
 
System check identified some issues:
 
WARNINGS:
?: (slippers.E001) Slippers was unable to find a components.yaml file.
	HINT: Make sure it's in a root template directory.
 ````
